# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93c69af43ef237139b4c6092aa5652800aeda2e62c3d61426788d25fe8e50d3c744ff430f68574b93b45037176d34f6af09f337dedc686a950546d667c903045

test:
  secret_key_base: 4e534fb84893e92a6f4ceb4a84fa65e3a5d482fc83090f6de50a54200a6d30aecec20464d28f204fd7d8fc59cd6c9042aba25bf4174ddde69658686d6b7962e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
